name: something

description: ok
branding:
  color: ffffff
  icon: alert-circle
  
inputs:
  - name: sample

configs:
  branches:
    - name: 1
      parameters:
        enforce-admins: true
  
  environments:
    - name: something
  
github-apps:
  - slug: ok
    parameters:
      environment: something

init:
  uses: test.yml
